---
name: Checks                                       # name that appears on GitHub Actions

on: [push]                                         # trigger

jobs:
  test-lint:                                       # id of the job
    name: Test and Lint                            # name to be displayed in github actions
    runs-on: ubuntu-20.04                          # OS runner (various runners available in GitHub Action site)
    steps:                                         # The orderly steps to be executed in GitHub Actions
      - name: Login to Docker Hub                  # Login into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout                             # to check if code is available
        uses: docker/login-action@v2
      - name: Test                                 # perform unit tests
        run: docker-compose run -rm app sh -c "python.py manage.py test"
      - name: Lint                                 # Linting
        run: docker-compose run -rm app sh -c "flake8"


